// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGw9rFwUEhh0G2PAzidtA_F38oWRVnNs',
    appId: '1:53647232373:web:88fa8d34fe8a76b411573c',
    messagingSenderId: '53647232373',
    projectId: 'sportplays-2b76f',
    authDomain: 'sportplays-2b76f.firebaseapp.com',
    databaseURL: 'https://sportplays-2b76f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sportplays-2b76f.appspot.com',
    measurementId: 'G-RF8TC1RL7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi5AvNwdwpflqIjrMzN_5m0c5BuYGBT5Q',
    appId: '1:53647232373:android:445c1eab5179119411573c',
    messagingSenderId: '53647232373',
    projectId: 'sportplays-2b76f',
    databaseURL: 'https://sportplays-2b76f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sportplays-2b76f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Rct_Fw-z80B-RK-e6oSIyLWQvmzvCHI',
    appId: '1:53647232373:ios:4c5ca4a7389b34fb11573c',
    messagingSenderId: '53647232373',
    projectId: 'sportplays-2b76f',
    databaseURL: 'https://sportplays-2b76f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sportplays-2b76f.appspot.com',
    iosBundleId: 'com.example.sportplays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Rct_Fw-z80B-RK-e6oSIyLWQvmzvCHI',
    appId: '1:53647232373:ios:619cbd903b3dea5511573c',
    messagingSenderId: '53647232373',
    projectId: 'sportplays-2b76f',
    databaseURL: 'https://sportplays-2b76f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sportplays-2b76f.appspot.com',
    iosBundleId: 'com.example.sportplays.RunnerTests',
  );
}
