name: sportplays
description: A new Flutter project
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  date_time_picker: ^2.0.0
  flutter_local_notifications: ^9.1.3
  razorpay_flutter: ^1.2.5
  fluttertoast: ^8.0.3
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  get: ^4.6.1
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  font_awesome_flutter: ^9.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - images/
    - images/logo.png
    - images/badminton.png
    - images/pingpong.png
    - images/squash.png
    - images/sporthall.png
